#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys
import tempfile
import subprocess

from drenv import kubectl
from argocdenv import get_argocd_env


def deploy_guestbook(cluster):
    print(f"Deploying application guestbook in namespace argocd-test on cluster {cluster}")
    # Need switch to hub cluster argocd ns first, otherwise will hit argocd bug
    # see https://github.com/argoproj/argo-cd/issues/14167
    with tempfile.TemporaryDirectory(prefix="drenv-argocd.") as tmpdir:
        env=get_argocd_env(tmpdir, cluster)
        # The following commands use subprocess.run since commamnds.run/watch
        # do not support setting child process environment.
        # TODO: add env argumnet to commands.run/watch.
        subprocess.run(
            [
                "argocd",
                "app",
                "create",
                "guestbook",
                "--repo=https://github.com/argoproj/argocd-example-apps.git",
                "--path=guestbook",
                "--dest-server=https://kubernetes.default.svc",
                "--dest-namespace=argocd-test",
                "--sync-option=CreateNamespace=true",
                "--sync-policy=automated",
            ],
            check=True,
            env=env,
        )


def wait_until_guestbook_is_healthy(cluster):
    print("Waiting application guestbook to be healthy")
    kubectl.wait(
        "application",
        "guestbook",
        "--for=jsonpath={.status.health.status}=Healthy",
        "--namespace=argocd",
        "--timeout=60s",
        context=cluster,
    )


def undeploy_guestbook(cluster):
    print("Deleting application guestbook")
    # Need switch to hub cluster argocd ns first, otherwise will hit argocd bug
    # see https://github.com/argoproj/argo-cd/issues/14167
    with tempfile.TemporaryDirectory(prefix="drenv-argocd.") as tmpdir:
        env=get_argocd_env(tmpdir, cluster)
        # The following commands use subprocess.run since commamnds.run/watch
        # do not support setting child process environment.
        # TODO: add env argumnet to commands.run/watch.
        subprocess.run(
            ["argocd", "app", "delete", "guestbook", "--yes", "--wait"],
            check=True,
            env=env,
        )
    kubectl.delete("namespace", "argocd-test", context=cluster)


if len(sys.argv) != 4:
    print(f"Usage: {sys.argv[0]} hub cluster1 cluster2")
    sys.exit(1)

hub = sys.argv[1]

deploy_guestbook(hub)
wait_until_guestbook_is_healthy(hub)
undeploy_guestbook(hub)
