#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import sys

from drenv import kubectl
from drenv import commands


def deploy_guestbook(cluster):
    commands.run(
        "argocd",
        "app",
        "create",
        "guestbook",
        "--repo",
        "https://github.com/argoproj/argocd-example-apps.git",
        "--path",
        "guestbook",
        "--dest-server",
        "https://kubernetes.default.svc",
        "--dest-namespace",
        "argo-test",
        "--sync-option",
        "CreateNamespace=true",
        "--sync-policy",
        "automated",
        "--kube-context",
        cluster,
    )


def wait_until_guestbook_is_healthy(cluster):
    print("Waiting application to be healthy")
    kubectl.wait(
        "application",
        "guestbook",
        "--for=jsonpath={.status.health.status}=Healthy",
        "--namespace=argocd",
        "--timeout=60s",
        context=cluster,
    )


def undeploy_guestbook(cluster):
    commands.run(
        "argocd", "app", "delete", "guestbook", "--yes", "--kube-context", cluster
    )


if len(sys.argv) != 4:
    print(f"Usage: {sys.argv[0]} hub cluster1 cluster2")
    sys.exit(1)

hub = sys.argv[1]

deploy_guestbook(hub)
wait_until_guestbook_is_healthy(hub)
undeploy_guestbook(hub)
