---
channelname: "ramen-gitops"
channelnamespace: "ramen-samples"
giturl: "https://github.com/nirs/ocm-ramen-samples.git"
pvcspecs:
  - storageclassname: rook-cephfs
    accessmodes: ReadWriteMany
  - storageclassname: rook-ceph-block
    accessmodes: ReadWriteOnce
