---
channelname: "ramen-gitops"
channelnamespace: "ramen-samples"
giturl: "https://github.com/RamenDR/ocm-ramen-samples.git"

pvcs:
  - storageclassname: rook-cephfs
    accessModes: ReadWriteMany
  - storageclassname: rook-ceph-block
    accessModes: ReadWriteOnce
